### ISSUE TITLE
Deal with empty directories appropriately

### ISSUE THREAD

**Issue by hakbailey** [hakbailey/handbag#10]
Decision still needs to be made: either do not allow empty directories to be added to the payload (in which case there should be a notification to the user) or add a new option to the workflow profile to keep or discard empty directories.

Either way, there's a bug to be fixed around empty directories. Currently, when an empty directory and additional directories with files are added to the payload at the same time, the empty directory gets populated with the other files.

**Comment by richardrodgers** [comment]
Can you describe the bug scenario a bit more? Is it when a directory tree containing empty sub-directories is dragged in, or does one need to drag in an empty directory, _then_ other stuff (directories or files)? A sequence of steps to reproduce the bug

**Comment by hakbailey** [comment]
I just got this message from Jessica: "Just tried to handbag a set of files with a metadata folder and objects folder, but without empty logs directory. HandBag put the objects folder into the metadata folder." So it may not just be empty directories. Will attempt to recreate the issue this week and figure out exactly what's going on.
